db = {
    1 : ("Agente speciale Alfa",
         "Antonio Serra", 
         "Antonio Serra", 
         "Claudio Castellini", 
         "Claudio Castellini"),
    2 : ("Il Monolito Nero",
         "Antonio Serra, Michele Medda, Bepi Vigna",
         "Antonio Serra, Michele Medda, Bepi Vigna",
         "Germano Bonazzi",
         "Claudio Castellini"),
    3 : ("Operazione Drago",
         "Bepi Vigna",
         "Bepi Vigna",
         "Stefano Casini",
         "Claudio Castellini"),
    4 : ("L'isola della morte",
         "Bepi Vigna",
         "Bepi Vigna",
         "Stefano Casini",
         "Claudio Castellini"),
    5 : ("Forza invisibile",
         "Michele Medda",
         "Michele Medda",
         "Romeo Toffanetti",
         "Claudio Castellini"),
    6 : ("Terrore sotto zero",
         "Bepi Vigna",
         "Bepi Vigna",
         "Germano Bonazzi",
         "Claudio Castellini"),
    7 : ("La zona proibita",
         "Antonio Serra",
         "Antonio Serra",
         "Nicola Mari",
         "Claudio Castellini"),
    8 : ("Uomini Ombra",
         "Antonio Serra",
         "Antonio Serra",
         "Nicola Mari",
         "Claudio Castellini"),
    9 : ("Gli occhi di uno sconosciuto",
         "Michele Medda",
         "Michele Medda",
         "Stefano Casini",
         "Claudio Castellini"),
    10 : ("Inferno",
          "Bepi Vigna",
          "Bepi Vigna",
          "Dante Bastianoni",
          "Claudio Castellini")
}
